INSERT INTO users (name,email,password_hash,role) VALUES
('Admin','admin@example.com','$2b$12$uNVIPgjH/ydkXxziziHcNur.dRMAs6fZFDgNEFAIjVQkYFkbLTqNq','ADMIN');

INSERT INTO `products` (`id`, `name`, `price`, `description`, `image_url`, `rating_avg`, `rating_count`, `created_at`, `updated_at`) VALUES
(5, 'Fone de ouvido RGB', 499.90, 'Headset Gamer RGB 7.1\r\n\r\nCor: Preto com iluminação RGB vibrante\r\n\r\nSom surround 7.1 para imersão total nos jogos\r\n\r\nMicrofone ajustável com redução de ruído\r\n\r\nAlmofadas macias e confortáveis para longas sessões\r\n\r\nArco ajustável para melhor encaixe\r\n\r\nIdeal para gamers que buscam qualidade de áudio e estilo', '/commerce-module/public/assets/img/headset.png', 4.1, 666, '2025-08-26 17:13:33', '2025-08-27 14:14:08'),
(6, 'Camiseta Megaman X6', 149.90, 'Camiseta Mega Man X6\r\n\r\nCor: Preta\r\n\r\nMaterial: Algodão de alta qualidade\r\n\r\nEstampa exclusiva com X e Zero (Mega Man X6)\r\n\r\nConfortável e durável\r\n\r\nIdeal para fãs de games e estilo casual', '/commerce-module/public/assets/img/megamanx6.png', 4.8, 250, '2025-08-27 13:43:09', '2025-08-27 13:43:09'),
(7, 'Mousepad Valorant', 50.00, 'Mousepad Gamer Valorant\r\n\r\nCor: Preto com estampa oficial em vermelho\r\n\r\nMaterial: Superfície em tecido premium e base antiderrapante emborrachada\r\n\r\nBordas reforçadas para maior durabilidade\r\n\r\nEstampa vibrante com logotipo do jogo Valorant\r\n\r\nIdeal para jogos de alta precisão e longas sessões de uso', '/commerce-module/public/assets/img/valorant.png', 4.3, 5000, '2025-08-27 13:45:24', '2025-08-27 13:48:06'),
(8, 'Boné Super Mario Bros', 100.00, 'Boné Super Mario Bros\r\n\r\nCor: Azul marinho com aba vermelha\r\n\r\nMaterial: Tecido resistente e confortável\r\n\r\nEstampa bordada oficial Super Mario Bros na parte frontal\r\n\r\nAba curva para melhor proteção solar\r\n\r\nAjustável, tamanho único\r\n\r\nIdeal para fãs da Nintendo e estilo casual gamer', '/commerce-module/public/assets/img/mario.png', 4.7, 4752, '2025-08-27 13:51:44', '2025-08-27 13:51:44'),
(9, 'Moletom League of Legends', 349.90, 'Moletom League of Legends\r\n\r\nCor: Preto\r\n\r\nMaterial: Algodão e poliéster de alta qualidade\r\n\r\nEstampa oficial League of Legends em dourado e branco\r\n\r\nGola com capuz ajustável e bolso canguru frontal\r\n\r\nConfortável, macio e ideal para o dia a dia ou sessões de jogo\r\n\r\nPerfeito para fãs do universo LoL', '/commerce-module/public/assets/img/lol.png', 5.0, 8752, '2025-08-27 13:54:33', '2025-08-27 13:54:33'),
(10, 'Camiseta The Witcher', 149.90, 'Camiseta The Witcher\r\n\r\nCor: Preta\r\n\r\nMaterial: Algodão macio e resistente\r\n\r\nEstampa oficial The Witcher com Geralt de Rívia em destaque\r\n\r\nDesign detalhado e de alta qualidade\r\n\r\nConfortável para uso diário\r\n\r\nIdeal para fãs da saga de jogos e da série', '/commerce-module/public/assets/img/witcher.png', 5.0, 10547, '2025-08-27 13:58:24', '2025-08-27 13:58:24'),
(11, 'Camiseta Dragon Ball Z', 149.90, 'Camiseta Dragon Ball Z – Goku Super Saiyajin\r\n\r\nCor: Preta\r\n\r\nMaterial: Algodão macio e resistente\r\n\r\nEstampa oficial Dragon Ball Z com Goku Super Saiyajin\r\n\r\nDesign vibrante e de alta qualidade\r\n\r\nConfortável para uso diário\r\n\r\nPerfeita para fãs de anime e cultura geek', '/commerce-module/public/assets/img/dbz.png', 4.8, 17522, '2025-08-27 14:03:16', '2025-08-27 14:03:16'),
(12, 'Moletom Need for Speed', 349.90, 'Moletom Need for Speed\r\n\r\nCor: Preto\r\n\r\nMaterial: Algodão e poliéster de alta qualidade\r\n\r\nEstampa oficial Need for Speed em azul e rosa neon\r\n\r\nCapuz ajustável com cordão e bolso canguru frontal\r\n\r\nConfortável, macio e ideal para uso diário ou sessões de jogo\r\n\r\nPerfeito para fãs da clássica franquia de corrida', '/commerce-module/public/assets/img/nfs.png', 4.5, 13024, '2025-08-27 14:04:45', '2025-08-27 14:04:45'),
(13, 'Tênis RGB', 499.90, 'Tênis Gamer RGB\r\n\r\nCor: Preto com detalhes em LED RGB multicolorido\r\n\r\nDesign moderno e futurista, inspirado no estilo gamer\r\n\r\nSolado robusto e confortável para uso diário\r\n\r\nIluminação vibrante nas laterais e entressola\r\n\r\nMaterial resistente e de alta durabilidade\r\n\r\nIdeal para quem busca estilo único e visual gamer inovador', '/commerce-module/public/assets/img/rgb.png', 4.7, 7500, '2025-08-27 14:06:16', '2025-08-27 14:06:16'),
(14, 'Calça Jogger Gamer', 299.90, 'Calça Jogger Gamer\r\n\r\nCor: Azul marinho, preto e detalhes em verde neon\r\n\r\nMaterial: Tecido leve, confortável e resistente\r\n\r\nEstampa temática gamer moderna na lateral\r\n\r\nCintura elástica com cordão ajustável\r\n\r\nPunhos canelados para melhor ajuste\r\n\r\nIdeal para uso casual ou estilo streetwear gamer', '/commerce-module/public/assets/img/calça.png', 4.8, 12000, '2025-08-27 14:07:37', '2025-08-27 14:07:37'),
(15, 'Boné Hollow Knight', 100.00, 'Boné Hollow Knight\r\n\r\nCor: Preto\r\n\r\nMaterial: Tecido resistente e confortável\r\n\r\nEstampa bordada oficial Hollow Knight na parte frontal\r\n\r\nAba reta estilizada\r\n\r\nAjustável, tamanho único\r\n\r\nIdeal para fãs do jogo e para compor looks casuais gamer', '/commerce-module/public/assets/img/hollow.png', 4.3, 3753, '2025-08-27 14:09:02', '2025-08-27 14:09:02'),
(16, 'Jaqueta Cyberpunk 2077', 499.90, 'Jaqueta Cyberpunk 2077\r\n\r\nCor: Preta com detalhes em neon (amarelo, azul e rosa)\r\n\r\nMaterial: Tecido sintético resistente e confortável\r\n\r\nEstampa oficial Cyberpunk 2077 na parte frontal\r\n\r\nFechamento em zíper e punhos ajustados\r\n\r\nDesign futurista inspirado no universo do jogo\r\n\r\nIdeal para fãs que querem estilo e autenticidade gamer', '/commerce-module/public/assets/img/cyber.png', 4.6, 28452, '2025-08-27 14:10:50', '2025-08-27 14:10:50');

